# Enhanced RL Trading System Configuration

# Environment settings
environment:
  # Portfolio settings
  initial_cash: 2000000  # Starting capital in INR
  episode_length: 60     # Trading days per episode
  warmup_period: 50      # Historical data needed before trading
  
  # Position limits
  max_position_per_stock: 100  # Maximum shares per stock
  min_trade_value: 10000       # Minimum trade value in INR
  position_limit_pct: 0.20     # Max 20% of portfolio per position
  
  # Risk management
  max_drawdown_limit: 0.10     # 10% maximum drawdown
  daily_loss_limit: 0.02       # 2% daily loss limit
  
  # Trading costs
  transaction_cost: 0.001      # 0.1% per trade
  stt_rate: 0.0015            # Securities Transaction Tax

# Asset universe
assets:
  stocks:
    - RELIANCE.NS
    - TCS.NS
    - HDFCBANK.NS
    - INFY.NS
    - ICICIBANK.NS
  
  # Data settings
  data_period: 2y              # Historical data period
  data_interval: 1d            # Daily data

# Agent architecture
agent:
  # Network dimensions
  hidden_dim: 512              # Hidden layer size
  lstm_hidden: 256             # LSTM hidden size (if using V3)
  n_attention_heads: 8         # Number of attention heads
  dropout_rate: 0.1            # Dropout probability
  
  # Asset processors
  asset_hidden_dim: 256        # Hidden dim for asset-specific layers
  asset_output_dim: 128        # Output dim for asset processors

# Training settings
training:
  # Basic parameters
  n_episodes: 1500             # Number of training episodes
  batch_size: 128              # Batch size for updates
  n_epochs: 10                 # Epochs per update
  n_steps: 1024                # Steps per trajectory collection
  
  # Learning rates
  learning_rate: 5e-5          # Initial learning rate
  lr_min: 1e-6                 # Minimum learning rate
  lr_decay: 0.999              # Learning rate decay
  
  # PPO parameters
  gamma: 0.99                  # Discount factor
  gae_lambda: 0.95             # GAE lambda
  clip_epsilon: 0.2            # PPO clip parameter
  clip_decay: 0.999            # Clip decay rate
  
  # Loss coefficients
  value_coef: 0.5              # Value loss coefficient
  entropy_coef: 0.05           # Entropy bonus
  entropy_min: 0.001           # Minimum entropy
  
  # Optimization
  max_grad_norm: 0.5           # Gradient clipping
  target_kl: 0.02              # KL divergence threshold
  
  # Regularization
  weight_decay: 0.0001         # L2 regularization

# Position sizing
position_sizing:
  max_position_pct: 0.25       # Max 25% Kelly fraction
  confidence_threshold: 0.6     # Minimum confidence for full size
  kelly_safety_factor: 0.25    # Kelly fraction multiplier
  trade_history_window: 100    # Trades to consider for Kelly

# Technical indicators
indicators:
  # Momentum
  rsi_period: 14
  momentum_periods: [10, 21]
  
  # Moving averages
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  
  # Volatility
  bb_period: 20
  bb_std: 2
  atr_period: 14
  volatility_windows: [21, 63]
  
  # Market analysis
  market_ma_period: 20
  correlation_window: 60

# Evaluation settings
evaluation:
  n_test_episodes: 30          # Episodes for final evaluation
  test_epsilon: 0.05           # Exploration during evaluation
  
  # Metrics
  risk_free_rate: 0.06         # Annual risk-free rate
  trading_days: 252            # Trading days per year

# Logging and checkpoints
logging:
  log_interval: 50             # Episodes between logs
  checkpoint_interval: 100     # Episodes between saves
  tensorboard: true            # Enable TensorBoard logging
  
  # Paths
  log_dir: logs/
  checkpoint_dir: checkpoints/
  results_dir: results/

# Visualization
visualization:
  figure_size: [16, 12]        # Default figure size
  dpi: 300                     # Image resolution
  save_plots: true             # Save plots to disk
  plot_format: png             # Image format

# System settings
system:
  seed: 42                     # Random seed
  device: auto                 # cuda/cpu/auto
  num_workers: 4               # Parallel workers
  pin_memory: true             # Pin memory for GPU